version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
volumes:
  db-data:
